version: '3'

services:  
   redis:
    image: "redis:alpine"
    command: redis-server 
    environment:
     - REDIS_REPLICATION_MODE=master
    ports:
     - "6379:6379"

   erua-issuer:
    image: endimion13/palaemon-embarkation:0.0.1c
    environment:
      NODE_ENV: "production"
      # for SSL: KEY_PATH:
      # for SSL: CERT_PATH:
      # for SSL: CERT_PASS:
      ENDPOINT: "http://localhost:5030"
      PORT: "5030"
      REDIS: "redis"
      ISSUER_URL: "https://dss1.aegean.gr/auth/realms/SSI"
      OIDC_REDIRECT_URI: "http://localhost:5030/login/callback"
      USER_INFO: "dss1.aegean.gr"
      USER_INFO_PORT: "8180"
    ports:
      - 5030:5030

